IF COL_LENGTH('USUARIO', 'DEBE_CAMBIAR_CONTRASENA') IS NULL
BEGIN
  ALTER TABLE [USUARIO]
  ADD [DEBE_CAMBIAR_CONTRASENA] bit NOT NULL
      CONSTRAINT [DF_USUARIO_DEBE_CAMBIAR_CONTRASENA] DEFAULT 1;
END;
