-- Borrado lógico de archivos en ARCHIVO_JUBILACION.
-- Aplica manualmente contra la base (mismo flujo que 202609180003, por P3005):
--   sqlcmd -S SRV-SQLDEV08 -d jubila -U <usuario> -P <pass> -C -i migration.sql

-- 1) Columnas nuevas
IF COL_LENGTH('ARCHIVO_JUBILACION', 'FECHA_ELIMINACION') IS NULL
BEGIN
  ALTER TABLE [ARCHIVO_JUBILACION]
  ADD [FECHA_ELIMINACION] datetime NULL;
END;

IF COL_LENGTH('ARCHIVO_JUBILACION', 'USUARIO_ELIMINACION') IS NULL
BEGIN
  ALTER TABLE [ARCHIVO_JUBILACION]
  ADD [USUARIO_ELIMINACION] int NULL;
END;

IF COL_LENGTH('ARCHIVO_JUBILACION', 'BIT_BORRADO') IS NULL
BEGIN
  ALTER TABLE [ARCHIVO_JUBILACION]
  ADD [BIT_BORRADO] bit NOT NULL
      CONSTRAINT [DF_ARCHIVO_JUBILACION_BIT_BORRADO] DEFAULT 0;
END;

-- 2) FK por si el usuario que elimina el archivo
IF NOT EXISTS (
  SELECT 1 FROM sys.foreign_keys
  WHERE name = 'fk_ARCHIVO_JUBILACION_USUARIO_ELIMINACION'
)
BEGIN
  ALTER TABLE [ARCHIVO_JUBILACION]
  ADD CONSTRAINT [fk_ARCHIVO_JUBILACION_USUARIO_ELIMINACION]
  FOREIGN KEY ([USUARIO_ELIMINACION])
  REFERENCES [USUARIO]([ID_USUARIO])
  ON UPDATE NO ACTION
  ON DELETE NO ACTION;
END;